openapi: 3.0.2
info:
  description: Get VWT travel information
  title: Travel information
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /Analyze:
    post:
      operationId: analyze_data
      responses:
        204:
          description: Analyze new data
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /CarsActivity:
    get:
      operationId: cars_activity_get
      responses:
        200:
          description: CarsActivity index
          content: 
            application/json:
              schema:
                type: object
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /CarsActivity/query:
    get:
      operationId: cars_activity_query_get
      responses:
        200:
          description: CarsActivity Grafana SimpleJson source
          content: 
            application/json:
              schema:
                type: object
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: cars_activity_query_post
      responses:
        204:
          description: Analyze new data
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /CarsActivity/{selected_date}:
    get:
      operationId: cars_activity_date_get
      parameters:
        - in: path
          name: selected_date
          schema:
            type: integer
            maximum: 29999999
          required: true
      responses:
        200:
          description: CarsActivity of specified date
          content:
            application/json:
              schema:
                type: object
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /StopLocations:
    get:
      operationId: stop_locations_get
      responses:
        200:
          description: CarsActivity index
          content: 
            application/json:
              schema:
                type: object
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /StopLocations/{selected_date}:
    get:
      operationId: stop_locations_date_get
      parameters:
        - in: path
          name: selected_date
          schema:
            type: integer
            maximum: 29999999
          required: true
      responses:
        200:
          description: CarsActivity of specified date
          content:
            application/json:
              schema:
                type: object
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    travelinfo:
      description: Travel information
      example:
        travel_distance: 340
        travel_time: 989
      properties:
        travel_distance:
          format: int32
          type: integer
        travel_time:
          format: int32
          type: integer
      title: Travel information
      type: object