openapi: 3.0.2
info:
  description: Get VWT travel information
  title: Travel information
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /travelinfo:
    get:
      operationId: travelinfo_get
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/travelinfo'
          description: Travel information
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /raininfluence:
    get:
      operationId: raininfluence_get
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/raininfluence'
          description: Influence of rain on work
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /firstblob:
    get:
      operationId: firstblob_get
      responses:
        200:
          content:
            application/json:
              schema: {}
          description: First blob containing work information
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /raininfo:
    get:
      operationId: raininfo_get
      responses:
        200:
          description: "Daily precipitation"
          content:
            text/csv:
              schema:
                $ref: '#/components/schemas/raininfo'
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    travelinfo:
      description: Travel information
      example:
        travel_distance: 340
        travel_time: 989
      properties:
        travel_distance:
          format: int32
          type: integer
        travel_time:
          format: int32
          type: integer
      title: Travel information
      type: object
    raininfluence:
      description: Describes influence of rain on work
      example:
        covariance: 0.3
        correlation: 0.5
        total_precipitation: 203
        total_work: 12454
      properties:
        covariance:
          format: float
          type: number
        correlation:
          format: float
          type: number
        total_precipitation:
          format: float
          type: number
        total_work:
          type: integer
      title: Rain influence
      type: object
    raininfo:
      title: Precipitation information
      description: Daily precipitation information
