openapi: 3.0.2
info:
  description: Get VWT travel information
  title: Travel information
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /travelinfo:
    get:
      operationId: travelinfo_get
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/travelinfo'
          description: Travel information
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /travelrequest:
    post:
      operationId: travelrequest_post
      requestBody:
        description: travelrequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/trip'
      responses:
        '201':
          description: Created
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    travelinfo:
      description: Travel information
      example:
        trips:
        - departure: "2020-01-14T12:48"
          price: 100.00
          duration: 90
      properties:
        trips:
          type: array
          items:
            $ref: '#/components/schemas/trip'
    trip:
      properties:
        departure:
          format: date-time
          type: string
        price:
          format: int32
          type: integer
      title: Trip information
      type: object
