# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Flight(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, custormer_name=None, depart_from=None, start_time=None, duration=None, price=None):  # noqa: E501
        """Flight - a model defined in OpenAPI

        :param custormer_name: The custormer_name of this Flight.  # noqa: E501
        :type custormer_name: str
        :param depart_from: The depart_from of this Flight.  # noqa: E501
        :type depart_from: str
        :param start_time: The start_time of this Flight.  # noqa: E501
        :type start_time: datetime
        :param duration: The duration of this Flight.  # noqa: E501
        :type duration: int
        :param price: The price of this Flight.  # noqa: E501
        :type price: int
        """
        self.openapi_types = {
            'custormer_name': str,
            'depart_from': str,
            'start_time': datetime,
            'duration': int,
            'price': int
        }

        self.attribute_map = {
            'custormer_name': 'custormer_name',
            'depart_from': 'depart_from',
            'start_time': 'start_time',
            'duration': 'duration',
            'price': 'price'
        }

        self._custormer_name = custormer_name
        self._depart_from = depart_from
        self._start_time = start_time
        self._duration = duration
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Flight':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The flight of this Flight.  # noqa: E501
        :rtype: Flight
        """
        return util.deserialize_model(dikt, cls)

    @property
    def custormer_name(self):
        """Gets the custormer_name of this Flight.


        :return: The custormer_name of this Flight.
        :rtype: str
        """
        return self._custormer_name

    @custormer_name.setter
    def custormer_name(self, custormer_name):
        """Sets the custormer_name of this Flight.


        :param custormer_name: The custormer_name of this Flight.
        :type custormer_name: str
        """

        self._custormer_name = custormer_name

    @property
    def depart_from(self):
        """Gets the depart_from of this Flight.


        :return: The depart_from of this Flight.
        :rtype: str
        """
        return self._depart_from

    @depart_from.setter
    def depart_from(self, depart_from):
        """Sets the depart_from of this Flight.


        :param depart_from: The depart_from of this Flight.
        :type depart_from: str
        """

        self._depart_from = depart_from

    @property
    def start_time(self):
        """Gets the start_time of this Flight.


        :return: The start_time of this Flight.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this Flight.


        :param start_time: The start_time of this Flight.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def duration(self):
        """Gets the duration of this Flight.


        :return: The duration of this Flight.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this Flight.


        :param duration: The duration of this Flight.
        :type duration: int
        """

        self._duration = duration

    @property
    def price(self):
        """Gets the price of this Flight.


        :return: The price of this Flight.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this Flight.


        :param price: The price of this Flight.
        :type price: int
        """

        self._price = price
